/* modules-catalog.jsx — single source of truth for all SFA modules.
   Drives the hub home, sidebar, and any future module-aware UI. */

const MODULES = [
  {
    id: 'crop-book',
    name: 'ספר גידולים',
    sub: 'אינדקס פתוח של גידולים, זנים, מחזורי גידול',
    tier: 'open',
    icon: 'lettuce',
    thumb: 'module_thumb_book',
    stat: '66 גידולים · 242 זנים',
    color: 'leaf',
    href: '#crop-book',
  },
  {
    id: 'market',
    name: 'מחירון',
    sub: 'מדד מחירי תוצרת מנורמל יומי',
    tier: 'open',
    icon: 'tomato',
    thumb: 'module_thumb_market',
    stat: '30 מוצרים · 14 מקורות',
    color: 'tomato',
    href: '#market',
  },
  {
    id: 'calc',
    name: 'מחשבון לחקלאי',
    sub: 'תכנון רווחיות, שטחים, יבולים',
    tier: 'beta',
    icon: 'carrot',
    thumb: 'module_thumb_calc',
    stat: 'גרסת בטא · בפיתוח',
    color: 'sun',
    href: '#calc',
  },
  {
    id: 'planner',
    name: 'תכנון עונה',
    sub: 'ערוגות, רוטציה, לוח שתילה',
    tier: 'coming',
    icon: 'basil',
    thumb: 'module_thumb_plan',
    stat: 'בקרוב',
    color: 'leaf',
    href: '#planner',
  },
  {
    id: 'clients',
    name: 'ניהול לקוחות',
    sub: 'מנויי סלי תוצרת, חיובים, תקשורת',
    tier: 'paid',
    icon: 'cucumber',
    thumb: 'module_thumb_clients',
    stat: 'כלים מתקדמים',
    color: 'soil',
    href: '#clients',
  },
  {
    id: 'inventory',
    name: 'מעקב יבול ומלאי',
    sub: 'קצירה, אובדנים, מלאי קר',
    tier: 'paid',
    icon: 'strawberry',
    thumb: 'module_thumb_inv',
    stat: 'כלים מתקדמים',
    color: 'tomato',
    href: '#inventory',
  },
  {
    id: 'tend-bridge',
    name: 'חיבור Tend / חשבונית-ירוקה',
    sub: 'סנכרון חשבוניות והכנסות',
    tier: 'custom',
    icon: 'pepper',
    thumb: 'module_thumb_tend',
    stat: 'לפי החווה',
    color: 'soil',
    href: '#tend-bridge',
  },
  {
    id: 'field-log',
    name: 'יומן שדה',
    sub: 'תיעוד מזג אוויר, מחלות, טיפולים',
    tier: 'custom',
    icon: 'onion',
    thumb: 'module_thumb_field',
    stat: 'לפי החווה',
    color: 'leaf',
    href: '#field-log',
  },
];

// Tier definitions — single place to change copy / color
const TIERS = {
  open:   { label: 'כלים לקהילה',  short: 'קהילה',  color: 'leaf',   description: 'שירות ציבורי פתוח — נתונים מצרפיים, השוואת גורפים, בלי הרשמה ובלי תשלום. תרומה לקהילה החקלאית.' },
  beta:   { label: 'בטא · ניסיוני',  short: 'בטא',   color: 'sun',    description: 'בפיתוח פעיל. ייתכנו שינויים, מזמינים לתת פידבק.' },
  coming: { label: 'בקרוב',           short: 'בקרוב', color: 'paper',  description: 'אנחנו עובדים על זה. השאירו פרטים כדי לקבל הודעה כשנפתח.' },
  paid:   { label: 'כלים מתקדמים', short: 'בתשלום', color: 'soil',  description: 'יכולות תפעוליות מורחבות לחוות פעילות — תמחור לפי גודל ושימוש.' },
  custom: { label: 'בדיוק לחווה שלך',  short: 'בהזמנה', color: 'tomato', description: 'אינטגרציות וכלים מותאמים אישית — דברו איתנו, נתפור עבורכם.' },
};

Object.assign(window, { MODULES, TIERS });
