"""055: WP-C5 Phase A — data cleanup (basil + tomato + beans consolidation).

Per DECISION_RECORD_SFA-S003-P002-WP-C5_v1.0.0:
  - Decision 1: Basil — MERGE crop 58 (בזיליקום) → crop 4 (בזיל)
  - Decision 2: Tomato — Option A (keep crops 49+73 separated; merge orphans)
  - Decision 3: Beans — MERGE crops 59+60 → crop 6, default = מטפסת

This migration is **NON-REVERSIBLE** (data merge). Downgrade is a no-op
with a logged warning — restore from backup if rollback needed.

Idempotency strategy:
  - Every UPDATE/DELETE is guarded with WHERE-exists so re-runs are safe.
  - Source-value merges use INSERT...ON CONFLICT DO NOTHING to respect
    UNIQUE(variety_id, field_name, source); conflicting rows are kept on
    the target (default) variety per DECISION_RECORD §2.

Cascade map (verified against live DB columns 2026-05-28):
  - crop_varieties.crop_id → crops.id (NO cascade)        → repoint manually
  - crop_variety_source_values.variety_id → cascade       → migrate then auto-drop
  - crop_field_enrichment.variety_id → cascade            → regenerated by runner
  - crop_task_templates.crop_id → cascade                 → repoint to target crop
  - crop_knowledge_notes.crop_id → cascade (nullable)     → repoint to target crop
  - crop_knowledge_notes_crops.crop_id → cascade          → repoint to target crop
  - crop_planting_calendar.crop_id → cascade              → repoint to target crop
  - crop_companion_matrix.crop_a_id/crop_b_id → cascade   → repoint to target crop
  - crop_postharvest_storage.crop_id → cascade            → repoint to target crop
  - crop_cover_crops: STANDALONE (no crop_id FK; see migration 050) — skip

Revision ID: 055
Revises: 054
Create Date: 2026-05-28
"""
from alembic import op

revision = "055"
down_revision = "054"
branch_labels = None
depends_on = None


# ---------------------------------------------------------------------------
# Helper SQL templates
# ---------------------------------------------------------------------------

# Merge all source-values from source variety to target variety, then drop
# the source variety (cascade clears its leftover sv rows).
_MERGE_VARIETY_SQL = """
INSERT INTO crop_variety_source_values
  (variety_id, field_name, source, value_text, value_numeric, unit, note,
   trust_tier, confidence_weight, is_outlier_rejected)
SELECT
  :target_vid, field_name, source, value_text, value_numeric, unit, note,
  trust_tier, confidence_weight, is_outlier_rejected
FROM crop_variety_source_values
WHERE variety_id = :source_vid
ON CONFLICT (variety_id, field_name, source) DO NOTHING;

DELETE FROM crop_variety_source_values WHERE variety_id = :source_vid;
DELETE FROM crop_field_enrichment      WHERE variety_id = :source_vid;
DELETE FROM crop_varieties             WHERE id = :source_vid;
"""

# Per-table dedup-then-update.  Each cascade table has a UNIQUE constraint
# that can collide when source-crop rows are repointed to an already-
# populated target-crop; we DELETE the would-be-duplicates from the source
# first, then UPDATE the survivors.  Unique constraints inspected
# 2026-05-28 from live DB:
#   crop_task_templates       UNIQUE (crop_id, source, task_type, days_offset)
#   crop_knowledge_notes      UNIQUE (crop_id, source, note_type)
#   crop_knowledge_notes_crops PRIMARY KEY (note_id, crop_id)
#   crop_planting_calendar    UNIQUE (crop_id, source, activity_type)
#   crop_companion_matrix     UNIQUE (crop_a_id, crop_b_id, source)
#   crop_postharvest_storage  UNIQUE (crop_id, source)
#
# crop_varieties has UNIQUE (crop_id, name_en) — dedup'd in the inline
# basil / beans logic above (re-parenting with is_default=FALSE; the
# variety_id stays unique).
_REPOINT_SQLS = [
    # crop_task_templates
    """
    DELETE FROM crop_task_templates s
    WHERE s.crop_id = :source_cid
      AND EXISTS (
        SELECT 1 FROM crop_task_templates t
        WHERE t.crop_id = :target_cid
          AND t.source = s.source
          AND t.task_type = s.task_type
          AND t.days_offset = s.days_offset
      );
    """,
    "UPDATE crop_task_templates SET crop_id = :target_cid WHERE crop_id = :source_cid;",

    # crop_knowledge_notes
    """
    DELETE FROM crop_knowledge_notes s
    WHERE s.crop_id = :source_cid
      AND EXISTS (
        SELECT 1 FROM crop_knowledge_notes t
        WHERE t.crop_id = :target_cid
          AND t.source = s.source
          AND t.note_type = s.note_type
      );
    """,
    "UPDATE crop_knowledge_notes SET crop_id = :target_cid WHERE crop_id = :source_cid;",

    # crop_knowledge_notes_crops (junction; PK = (note_id, crop_id))
    """
    DELETE FROM crop_knowledge_notes_crops s
    WHERE s.crop_id = :source_cid
      AND EXISTS (
        SELECT 1 FROM crop_knowledge_notes_crops t
        WHERE t.crop_id = :target_cid AND t.note_id = s.note_id
      );
    """,
    "UPDATE crop_knowledge_notes_crops SET crop_id = :target_cid WHERE crop_id = :source_cid;",

    # crop_planting_calendar
    """
    DELETE FROM crop_planting_calendar s
    WHERE s.crop_id = :source_cid
      AND EXISTS (
        SELECT 1 FROM crop_planting_calendar t
        WHERE t.crop_id = :target_cid
          AND t.source = s.source
          AND t.activity_type = s.activity_type
      );
    """,
    "UPDATE crop_planting_calendar SET crop_id = :target_cid WHERE crop_id = :source_cid;",

    # crop_companion_matrix (two-FK pair table).  Handle crop_a_id then crop_b_id.
    """
    DELETE FROM crop_companion_matrix s
    WHERE s.crop_a_id = :source_cid
      AND EXISTS (
        SELECT 1 FROM crop_companion_matrix t
        WHERE t.crop_a_id = :target_cid
          AND t.crop_b_id = s.crop_b_id
          AND t.source = s.source
      );
    """,
    "UPDATE crop_companion_matrix SET crop_a_id = :target_cid WHERE crop_a_id = :source_cid;",
    """
    DELETE FROM crop_companion_matrix s
    WHERE s.crop_b_id = :source_cid
      AND EXISTS (
        SELECT 1 FROM crop_companion_matrix t
        WHERE t.crop_b_id = :target_cid
          AND t.crop_a_id = s.crop_a_id
          AND t.source = s.source
      );
    """,
    "UPDATE crop_companion_matrix SET crop_b_id = :target_cid WHERE crop_b_id = :source_cid;",

    # crop_postharvest_storage
    """
    DELETE FROM crop_postharvest_storage s
    WHERE s.crop_id = :source_cid
      AND EXISTS (
        SELECT 1 FROM crop_postharvest_storage t
        WHERE t.crop_id = :target_cid AND t.source = s.source
      );
    """,
    "UPDATE crop_postharvest_storage SET crop_id = :target_cid WHERE crop_id = :source_cid;",
]

# Run after dedup/repoints — crop_varieties has no source duplicate
# concern (the inline migrations above already moved them with
# is_default=FALSE).  But any LEFTOVER varieties in the source crop must
# also be repointed before the source crop can be deleted (FK enforces).
_FINAL_VARIETY_REPOINT_SQL = """
UPDATE crop_varieties
SET crop_id = :target_cid, is_default = FALSE
WHERE crop_id = :source_cid
  AND NOT EXISTS (
    SELECT 1 FROM crop_varieties t
    WHERE t.crop_id = :target_cid
      AND t.name_en IS NOT DISTINCT FROM crop_varieties.name_en
      AND t.id <> crop_varieties.id
  );
"""
# Any *remaining* varieties (those that would collide by name) get a
# deterministic suffix so the UNIQUE constraint holds.
_VARIETY_RENAME_AND_REPOINT_SQL = """
UPDATE crop_varieties
SET crop_id = :target_cid,
    is_default = FALSE,
    name_en = COALESCE(name_en, '') || ' (from crop ' || CAST(:source_cid AS text) || ')'
WHERE crop_id = :source_cid;
"""

_DELETE_SOURCE_CROP_SQL = "DELETE FROM crops WHERE id = :source_cid;"


def _merge_variety(bind, source_vid: int, target_vid: int) -> None:
    """Merge source variety's source-values into target, then drop source."""
    # Guard: skip if source variety no longer exists (idempotent).
    exists = bind.execute(
        # Use literal SQL — Alembic ops aren't conducive to parametric SELECT.
        # Safe: source_vid is an integer literal constructed here.
        # (We use exec_driver_sql via op.execute for the actual merges.)
        # SQLAlchemy core-level execute:
        # Use connection.execute with text() for portability.
        __import__("sqlalchemy").text(
            "SELECT 1 FROM crop_varieties WHERE id = :vid"
        ),
        {"vid": source_vid},
    ).first()
    if not exists:
        return
    sa = __import__("sqlalchemy")
    for stmt in _MERGE_VARIETY_SQL.strip().split(";"):
        s = stmt.strip()
        if not s:
            continue
        bind.execute(sa.text(s), {"source_vid": source_vid, "target_vid": target_vid})


def _repoint_crop(bind, source_cid: int, target_cid: int) -> None:
    """Repoint all FK references from source crop → target crop, then drop source crop.

    Uses dedup-then-update so UNIQUE constraints (crop_id + …) don't
    collide when the target crop already has a row for the same key.
    """
    sa = __import__("sqlalchemy")
    exists = bind.execute(
        sa.text("SELECT 1 FROM crops WHERE id = :cid"), {"cid": source_cid}
    ).first()
    if not exists:
        return
    params = {"source_cid": source_cid, "target_cid": target_cid}
    for raw in _REPOINT_SQLS:
        stmt = raw.strip()
        if not stmt:
            continue
        # Each entry is a single SQL statement; trailing ';' inside the
        # string is harmless for psycopg2.
        bind.execute(sa.text(stmt.rstrip(";")), params)

    # Repoint any remaining varieties (the basil + bean inline logic above
    # already moved targeted IDs; this catches anything left over).
    bind.execute(sa.text(_FINAL_VARIETY_REPOINT_SQL.rstrip(";")), params)
    bind.execute(sa.text(_VARIETY_RENAME_AND_REPOINT_SQL.rstrip(";")), params)

    bind.execute(sa.text(_DELETE_SOURCE_CROP_SQL.rstrip(";")), params)


def _delete_variety_if_exists(bind, vid: int) -> None:
    sa = __import__("sqlalchemy")
    bind.execute(sa.text("DELETE FROM crop_field_enrichment WHERE variety_id = :vid"),
                 {"vid": vid})
    bind.execute(sa.text("DELETE FROM crop_variety_source_values WHERE variety_id = :vid"),
                 {"vid": vid})
    bind.execute(sa.text("DELETE FROM crop_varieties WHERE id = :vid"), {"vid": vid})


def upgrade() -> None:
    bind = op.get_bind()
    if bind.dialect.name == "sqlite":
        # SQLite is used for unit tests only; production cleanup runs on
        # PostgreSQL.  Skip on SQLite so test envelopes that pre-load
        # different fixtures aren't disrupted.
        return

    sa = __import__("sqlalchemy")

    # ---------------------------------------------------------------------
    # DECISION #1 — Basil (crop 58 'בזיליקום' → crop 4 'בזיל')
    # ---------------------------------------------------------------------
    # Pre-snapshot 2026-05-28 against live DB (corrects DECISION_RECORD §1
    # ID typo — record said vid 461, actual single variety in crop 58 is
    # vid 477 with 9 sv):
    #   crop 58: 1 variety (vid 477, is_default=TRUE, 9 sv), 0 enrichment
    #   crop  4: 6 varieties, 32 sv, 71 enrichment
    # Strategy: re-parent crop-58's default variety to crop 4 as a
    # non-default variant (any vid still attached to crop 58 is treated
    # the same way — defensive), then repoint cascade-tables and drop crop 58.

    bind.execute(sa.text("""
        UPDATE crop_varieties
        SET crop_id = 4, is_default = FALSE
        WHERE crop_id = 58
    """))
    _repoint_crop(bind, source_cid=58, target_cid=4)

    # ---------------------------------------------------------------------
    # DECISION #2 — Tomato Option A
    # crop 49 (עגבנייה): merge anonymous + named-duplicate varieties → vid 233
    # crop 73 (עגבניית שרי): merge anonymous variants → vid 460
    # ---------------------------------------------------------------------
    # crop 49 merges (per DECISION_RECORD §Decision 2):
    for source_vid in (222, 403, 404, 405, 406):
        _merge_variety(bind, source_vid=source_vid, target_vid=233)
    # named duplicates:
    _merge_variety(bind, source_vid=227, target_vid=225)  # "montecarlo F.1" → "hyd. montecarlo F1"
    _merge_variety(bind, source_vid=229, target_vid=226)  # "Lobelo - חישתיל מורכב" → "Lobelo hyd. מורכב"

    # crop 73 merges → vid 460
    # NOTE: DECISION_RECORD §2 listed vid 477 here in error — that vid is
    # actually the basil-58 default (already handled by Decision #1).
    # Live DB shows crop 73 has 4 varieties: 443, 444, 445, 460.
    for source_vid in (443, 444, 445):
        _merge_variety(bind, source_vid=source_vid, target_vid=460)

    # ---------------------------------------------------------------------
    # DECISION #3 — Beans (default = מטפסת / Pole-Climbing)
    # crop 6 'שעועית' KEEP as primary; merge crops 59 (שעועית שיחית) +
    # 60 (שעועית מטפסת) into crop 6.
    # ---------------------------------------------------------------------
    # 1. Rename crop 6.name_en for clarity (default semantic explicit).
    bind.execute(sa.text("""
        UPDATE crops
        SET name_en = 'Beans (default: Pole/Climbing)'
        WHERE id = 6 AND name_en = 'Beans: Bush & Pole'
    """))

    # 2. crop 60 (שעועית מטפסת): the bulk of varieties are nonsense from a
    #    bad import (names like '●', '1', 'marketgardenerinstitute.com',
    #    'Intensive Spacing'); only vid 479 (default, 1 sv) is real.
    #
    # Delete the nonsense varieties first (those with 0 sv AND obviously
    # bad names).  Use a defensive name-list filter.
    bind.execute(sa.text("""
        DELETE FROM crop_field_enrichment
        WHERE variety_id IN (
            SELECT cv.id FROM crop_varieties cv
            WHERE cv.crop_id = 60
              AND cv.id != 479
              AND (
                cv.name_en IN ('●', '1', 'marketgardenerinstitute.com',
                               'Intensive Spacing', '', NULL)
                OR cv.name_en IS NULL
                OR cv.name_en ~ '^[●•\\*\\-\\s]+$'
              )
              AND NOT EXISTS (
                SELECT 1 FROM crop_variety_source_values sv
                WHERE sv.variety_id = cv.id
              )
        )
    """))
    bind.execute(sa.text("""
        DELETE FROM crop_varieties cv
        WHERE cv.crop_id = 60
          AND cv.id != 479
          AND (
            cv.name_en IN ('●', '1', 'marketgardenerinstitute.com',
                           'Intensive Spacing', '')
            OR cv.name_en IS NULL
            OR cv.name_en ~ '^[●•\\*\\-\\s]+$'
          )
          AND NOT EXISTS (
            SELECT 1 FROM crop_variety_source_values sv
            WHERE sv.variety_id = cv.id
          )
    """))

    # 3. Merge crop 60 vid 479 (default with 1 sv) → crop 6 default.
    #    Find crop 6 default variety dynamically; fall back if absent.
    default_cv6 = bind.execute(sa.text("""
        SELECT id FROM crop_varieties
        WHERE crop_id = 6 AND is_default = TRUE
        ORDER BY id LIMIT 1
    """)).scalar()
    if default_cv6:
        _merge_variety(bind, source_vid=479, target_vid=default_cv6)

    # 4. Any remaining real varieties in crop 60 (post-nonsense-cleanup)
    #    that survived: re-parent them to crop 6 as non-default variants.
    bind.execute(sa.text("""
        UPDATE crop_varieties
        SET crop_id = 6, is_default = FALSE
        WHERE crop_id = 60
    """))

    # 5. crop 59 (שעועית שיחית): default = vid 476 (0 sv).  Re-parent
    #    as a non-default 'Bush variant' under crop 6.
    bind.execute(sa.text("""
        UPDATE crop_varieties
        SET crop_id = 6,
            is_default = FALSE,
            name_en = COALESCE(NULLIF(name_en, ''), 'Bush variant')
        WHERE id = 476 AND crop_id = 59
    """))
    bind.execute(sa.text("""
        UPDATE crop_varieties
        SET crop_id = 6, is_default = FALSE
        WHERE crop_id = 59
    """))

    # 6. Repoint any remaining crop-scoped rows (planting_calendar,
    #    knowledge_notes, etc.) from crops 59/60 → crop 6, then drop them.
    _repoint_crop(bind, source_cid=59, target_cid=6)
    _repoint_crop(bind, source_cid=60, target_cid=6)


def downgrade() -> None:
    # Data merge is non-reversible.  Restoring source crops/varieties +
    # untangling merged source-values requires a backup; not attempted here.
    raise NotImplementedError(
        "Migration 055 is NON-REVERSIBLE (data merge per DECISION_RECORD "
        "SFA-S003-P002-WP-C5 §Decisions 1-3).  Restore from backup to roll back."
    )
